### PR TITLE
 Fixed boolean icon handling in advanced screensaver implementation

### PR DESCRIPTION
**Pull request by fre4242**
When using the new "advanced screensaver" mode I've found that boolean values are using the wrong icon.
When the boolean value is true, then the _ScreensaverEntityIconOff_ is used and when it's false, the _ScreensaverEntityIconOn_ is used.
I think this is false and I would like to suggest to switch them. 
This PR provides the the change. I've also improved the readability of the code in HandleScreensaverUpdate().

### CODE REVIEW

**Comment by Armilar** [comment]
Did you see the PR from @bembelstemmer embelmern (Bender)?

https://github.com/joBr99/nspanel-lovelace-ui/pull/799

It is possible to set the target state for Boolean in the pageItem via  "val_best".

**Comment by fre4242** [comment]
Yes, I saw it and already used it. It works.
But this is only about the color of the icon, right? 
My suggestion is about the logic. I think the "Off"-Icon (ScreensaverEntityIconOff) should be used for a false state and the "On"-Icon for true state.

**Comment by bembelstemmer** [comment]
From my perspective it's a similar usecase but my change was about the coloring only.
I think val_best defines the meaning. So on or off can be the best (green color).
The different Icons for On and Off are a different thing though. On should be true and Off should be false to my mind at least.
Until now i haven't used different Icons for On and Off otherwise i might already had included that in PR.

**Comment by fre4242** [comment]
Because of problems with my fork having 6 commits instead of 2 I'll create a new one containing only the two. I'll close this one. Sorry for confusion.

**Pull request closed without merging**
