### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by Gerrit-KMeier**
Added a paragraph about how the color values a build. At least I never heard about it before.

### CODE REVIEW

**Comment by joBr99** [comment]
yeah it's rgb565 which is acually not uncommon on such low price embedded hardware like the nextion screen

I've embedded a color picker into this page of the documentation:

https://docs.nspanel.pky.eu/notifications/#color-picker

the color picker you've linked showes the result in hex and nextion needs it in decimal (even though there was also a color picker that I don't remember which outputs the color in dec)

**Comment by Gerrit-KMeier** [comment]
The colorpicker ist the best option. But it's not working (yet)

**Comment by joBr99** [comment]
What do you mean? The one on the documentation page works for me. On which browser/os is it broken?

**Comment by Gerrit-KMeier** [comment]
Yeah my fault. It's the FireFox 110 which has a slider for saturation. But this slide is initially zero which means black. So when selecting a color the initial black seemed like not being updated. The ColorPicker from Chrome is much more intuitive.
Mea culpa. Good job !

**Pull request closed without merging**
