### PR TITLE
Update pages.py

### PR DESCRIPTION
**Pull request by WhistleMaster**
Update pages.py for alarm_control_panel and sun entities.

### CODE REVIEW

**Review by joBr99 — CHANGES_REQUESTED** [review]
Hey, 
can you move the definition of the icons to the get_icon_id_ha function (defined in icons.py)
and the definition of the colors to the get_entity_color (defined in line 25 of pagey.py)

This ensures that the overwrite config options are working as expected.

**Comment by WhistleMaster** [comment]
Thanks ! Just committed a few changes, hope it's OK like that !

**Review by joBr99 — APPROVED** [review]
I've not tested it, but it looks good

**Comment by WhistleMaster** [comment]
Thanks !

**Comment by joBr99** [comment]
no, you don't have to do anything, just merged it

**Pull request merged**
