### PR TITLE
Add edge swipe functionality for page navigation in EU version.

### PR DESCRIPTION
**Pull request by matrixx567**
Hy,

today I have found some time to write an example implementation for my feature request #182 
I've implemented the edge swipe option. So if you swipe at the edge of the screen the corresponding button will be pressed.

On every card page I've added three hotspots on the edges `mSwipeNext`, `mSwipePrev` and `mSwipeUp`. The hotspots will check the used navigation in the local variable `tId.txt` and will click the corresponding button.
No code changes in other components are necessary to implement this feature.

For a better experience I've repositioned some buttons of the following cards:
- **cardThermo**: Fix the position of the `bPrev`and `bNext` button to match the other cards
- **cardMedia**: Decrease the width of the volume slider (4px) and move the volume up/down button 

It would be nice to give it a try. What do you think about this feature?

Martin

### CODE REVIEW

**Comment by joBr99** [comment]
Implementation looks good, would be nice if can you also add this to the US Portrait Version.

I will take care of the Landscape Version, before the next release.

**Comment by matrixx567** [comment]
I've allready added the US portrait version

**Comment by joBr99** [comment]
nice, just flashed this version to my panel, did you experiment with wider hotspots? 
an overlap with the navigation buttons shoudn't be a big issue

**Comment by matrixx567** [comment]
The left and right hotspots have the largest possible area that doesn't overlap with any other button on any card.
If you make the hotspots larger than it would act more like a button over the whole edge of the screen than as a swipe function. This could also be an option for an easier page navigation.

**Pull request merged**
