### PR TITLE
alternativeLayout Fix

### PR DESCRIPTION
**Pull request by illuzn**
It isn't pretty but this was the only way I could think to remap appropriate. There is probably a better way to do this.

### CODE REVIEW

**Comment by illuzn** [comment]
autoWeather capitalisation and argument (accepts `true` instead of `auto`) now corrected for consistency

**Comment by joBr99** [comment]
i fixed the color stuff for the alternative layout in the firmware, also modified behaviour of the portrait version for the alternative layout

**Comment by illuzn** [comment]
Hmm... I think the mapping of color to US portrait is broken because of differences between portrait and other modes.

From US-p screensaver.txt:
````
                                        //alternative layout
                                        //tMRIcon
                                        spstr strCommand.txt,tMRIcon.txt,"~",15
                                        if(tMRIcon.txt!="")
                                        {
                                            //value for tMRIcon, activate alternative layout
                                            vis tMainIcon,0
                                            vis tMainText,0
                                            vis tMainTextAlt,1
                                            vis tMainIconAlt,1
                                            vis tMRIcon,1
                                            vis tMR,1
                                        }
                                        //tMR
                                        spstr strCommand.txt,tMR.txt,"~",16
````

From EU screensaver.txt:
````
                                        //alternative layout
...
                                            //move forecast values to the right
                                            tForecast4.txt=tForecast3.txt
                                            tForecast3.txt=tForecast2.txt
                                            tForecast2.txt=tForecast1.txt
                                            tForecast4Val.txt=tForecast3Val.txt
                                            tForecast3Val.txt=tForecast2Val.txt
                                            tForecast2Val.txt=tForecast1Val.txt
                                            tF4Icon.txt=tF3Icon.txt
                                            tF3Icon.txt=tF2Icon.txt
                                            tF2Icon.txt=tF1Icon.txt
                                            tF4Icon.pco=tF3Icon.pco
                                            tF3Icon.pco=tF2Icon.pco
                                            tF2Icon.pco=tF1Icon.pco
````

**Comment by illuzn** [comment]
Never mind... I realised what was wrong fixed in #227

**Comment by joBr99** [comment]
Thanks for fixing it, there should no longer be a difference between the two layouts for the color command o.O

**Pull request merged**
